config/routes.rb
Rails.application.routes.draw do

  root 'shops#index'
  resources :shops 

  

  get "/spa" => "shops#spa" 

end

app/models/mrt.rb
class Mrt < ActiveRecord::Base
	serialize :data
end

app/models/mrt_station.rb
class MrtStation < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gmap_controller.rb
class GmapController < ApplicationController
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

	def index

		if params[:r_type]

			@r_type = params[:r_type]
			@station = Mrt.find(params[:mrt][:mrt_id])
			
			

			params = { category_filter: @r_type, sort:"1"}
			coordinates = {latitude: @station.latitude, longitude: @station.longitude}
			@shops = Yelp.client.search_by_coordinates(coordinates, params) 
		
		
		else
			params = {  }

			coordinates = {latitude: 25.030009, longitude: 121.472389}

			@shops = Yelp.client.search_by_coordinates(coordinates, params) 
		end

	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gmap_helper.rb
module GmapHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/gmap/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>
<script>
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": 0,
      "lng": 0,
      "picture": {
        "url": "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
        "width":  36,
        "height": 36
      },
      "infowindow": "hello!"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yelptest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 
</head>
<body>
<div class="text-center">
	<img width="800" height="300" src ="https://files.slack.com/files-pri/T03H88RF4-F06TG6UP6/chito_logo.jpg">
</div>
<%= yield %>

</body>
</html>

app/views/shops/index.html.erb
<div class = "container">
</br>
<%= form_tag shops_path , :method => :get ,:class=>"form-inline" do %>

<div class= "form-group">
<%= select_tag :r_type , options_for_select([['美式餐廳','burgers'], ['咖啡廳','cafes'], ['義式餐廳','italian']]) ,:prompt => "選擇餐廳類型",:class => "form-control"%>


<%= collection_select :mrt,:mrt_id, Mrt.all, :id, :name,  {:prompt => "選擇捷運站"} ,{:class =>"form-control" }%>

<%= submit_tag "搜尋" , :class => "btn btn-success"%>

<% end %>
</div>
</div>
</br>
<div class="container">
<table class= "table">
	<% @shops.businesses.each do |s| %>
	<tr>
		<% if s.respond_to?(:image_url) %>
  		<td><%= image_tag s.image_url ,:class => "img-circle"%></td>
		<% end %>
		<td><%= s.name %></td>
		<td><%= s.location.address.join("")%></td>
		<% if s.respond_to?(:display_phone) %>
			<td><%= s.display_phone %></td>
		<%end %>
		<td><%= s.rating %></td>
		<td><%= s.distance.to_i %>公尺</td>
		
	</tr>

	<% end %>


</table>
</div>

app/views/shops/spa.html.erb
<div id = "content">
ddd
</div>

<script>


$("#content").html( JST["templates/demo"]())
</script>